### ISSUE TITLE
README lacking usage instructions

### ISSUE THREAD

**Issue by TheOtterlord** [trevortylerlee/treelink#1]
Hi @trevortylerlee!

We've approved your theme in the Astro theme portal. We noticed your README doesn't contain much content. Ideally this should contain usage instructions (e.g. `npm create astro -- --template=...` steps to install dependencies, configure services, and build).

The formatting on your theme portal listing also seems a little wonky, but it's still readable, so we've approved it as is, but you might want to double-check it.

Thanks.

**Comment by trevortylerlee** [comment]
Thanks for the headsup -- I updated the README and the theme portal listing.
